feat(proxy_to_vkr): update to cosmwasm 1.1
astroport-fi/astro-generator-proxy-contracts pull request #13
Opened 2022-10-31 12:38 UTC by P-Yevhenii

2022-11-01 08:05 UTC, ShadoySV requested changes

2022-11-01 08:05 UTC, ShadoySV commented on contracts/proxy_to_vkr/examples/schema.rs
> +        migrate: MigrateMsg,
This should be linked to owned migrate message

2022-11-01 08:05 UTC, ShadoySV commented on contracts/proxy_to_vkr/Cargo.toml
> +authors = ["Astroport"]
Keep original authors

2022-11-01 12:46 UTC, ShadoySV requested changes

2022-11-01 12:46 UTC, ShadoySV commented on .github/workflows/code_coverage.yml
> +name: Code coverage
We don't need code coverage here

2022-11-01 12:46 UTC, ShadoySV commented on .github/workflows/tests_and_checks.yml
> +          python-version: 3.9.7
We don't need this

2022-11-01 13:14 UTC, ShadoySV approved these changes

2022-11-02 11:06 UTC, epanchee commented on .github/workflows/tests_and_checks.yml
> +          toolchain: 1.60.0
Lets use latest version: 1.64.0

2022-11-02 11:06 UTC, epanchee commented on contracts/proxy_to_vkr/Cargo.toml
> +valkyrie = { git = "https://github.com/valkyrieprotocol/contracts.git", branch = "feature/migrate_terra2"  }
I think better to pin exact version by commit hash, not by temporal branch

2022-11-03 08:58 UTC, merged